-- Migration: Initial Schema Setup for Cortex Enterprise AI ERP
-- Date: 2026-06-18
-- Enables pgvector and creates tables for HR, Accounting, and QA logs.

-- 1. Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Human Resources (HR) & Administration Table
CREATE TABLE IF NOT EXISTS employees (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(50),
    department VARCHAR(100) NOT NULL CHECK (department IN ('HR', 'Accounting', 'Marketing', 'Production', 'QA', 'Administration')),
    role VARCHAR(100) NOT NULL,
    hire_date DATE NOT NULL DEFAULT CURRENT_DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Accounting & Chartered Accountancy (CA) Ledger Table
-- Numeric type used for strict monetary accuracy to prevent floating point errors.
CREATE TABLE IF NOT EXISTS ledgers (
    ledger_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    account_name VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    amount NUMERIC(15, 2) NOT NULL CHECK (amount > 0),
    type VARCHAR(10) NOT NULL CHECK (type IN ('DEBIT', 'CREDIT')),
    category VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Production & Quality Assurance (QA) Technical Logs (Unstructured + Vector)
CREATE TABLE IF NOT EXISTS technical_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_id VARCHAR(100) NOT NULL,
    testing_engineer VARCHAR(150) NOT NULL,
    content TEXT NOT NULL,
    -- 1024-dimension matching NVIDIA NeMo Retriever embeddings
    embedding vector(1024),
    test_result VARCHAR(50) NOT NULL CHECK (test_result IN ('PASS', 'FAIL', 'INCONCLUSIVE')),
    logged_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. Indexes for Query Performance
CREATE INDEX IF NOT EXISTS idx_employees_department ON employees(department);
CREATE INDEX IF NOT EXISTS idx_ledgers_date ON ledgers(transaction_date);
CREATE INDEX IF NOT EXISTS idx_ledgers_category ON ledgers(category);

-- Create HNSW Vector index on technical_logs table for ultra-low latency semantic search
CREATE INDEX IF NOT EXISTS idx_technical_logs_hnsw_cosine
ON technical_logs
USING hnsw (embedding vector_cosine_ops);

-- 6. Helper RPC Function for Vector Similarity Search
-- This enables querying pgvector cosine similarity directly from the Supabase JS client.
CREATE OR REPLACE FUNCTION match_logs (
    query_embedding vector(1024),
    match_threshold float,
    match_count int
)
RETURNS TABLE (
    log_id bigint,
    component_id varchar,
    testing_engineer varchar,
    content text,
    test_result varchar,
    similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        technical_logs.log_id,
        technical_logs.component_id,
        technical_logs.testing_engineer,
        technical_logs.content,
        technical_logs.test_result,
        (1.0 - (technical_logs.embedding <=> query_embedding))::float AS similarity
    FROM technical_logs
    WHERE (1.0 - (technical_logs.embedding <=> query_embedding)) >= match_threshold
    ORDER BY technical_logs.embedding <=> query_embedding ASC
    LIMIT match_count;
END;
$$;
